### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by yjinbhhs** [APPIAN-PET/APPIAN#37]
Hi,

When I installed the software, I met the error in the attached screenshot. It seems that the package is missing "ModuleNotFoundError: No module named 'sklearn.neighbors.kde". Please see the screenshot for details.
![error2](https://user-images.githubusercontent.com/21111879/124109222-e92b0f80-da34-11eb-951a-9535f460b01b.JPG)

**Comment by tfunck** [comment]
Hi, thank you very much for the bug report. I believe the issue should be fixed now. Please try again and let me know how it goes.
Cheers
Thomas

**Comment by yjinbhhs** [comment]
Hi Thomas,

Sorry for the late reply. I was out of town for a few months. I tried the new version, and the problem persists. I attached the screen shot here. Could you please take a look? Thanks!

![error3](https://user-images.githubusercontent.com/21111879/131758769-4b8e53db-2c81-4b24-bbc8-4c53e95cd30f.JPG)

**Comment by tfunck** [comment]
Thanks for the update. I'm pretty sure this code is fixed in the code but I didn't create a new singularity image. The interface for singularity hub has changed and now uses data lad, which I don't know how to use yet. I'll give it a go this weekend and get back to you.

**Comment by yjinbhhs** [comment]
Thank you! I actually did a pull with your docker image by " singularity pull docker://tffunck/appian:latest-dev",  and then run the save the .sif image with the above command. I got the following error as well. But this error was different than the one above. Basically, both docker and singularity images won't work on singularity.

Do you have an email address that I can use to contact you since I am a newbie on APPIAN? I have a few other questions on how to use APPIAN. Can I write it to your Forschungszentrum Jülich email address? Thank you!
![error3](https://user-images.githubusercontent.com/21111879/132910670-4e674105-7028-44ed-8d5f-736acd0f98f9.JPG)

**Comment by yjinbhhs** [comment]
Hi, I managed to use singularity to pull the docker image, and I also used docker as well. I downloaded the sample data. I used the following command, and the program just wouldn't run (I also used docker run -it as well, the same error). Could you please test your commands to make sure that it works? It doesn't work for me.

**yjin@c2023-> singularity exec appian_latest-dev.sif bash -c "python3 /opt/APPIAN/Launcher.py --sub 00101 --ses baseline --user-ants-command /opt/APPIAN/src/ants_command_quick.txt -s ds001705-download/ -t out_ds001705-download/ "**

/usr/local/lib/python3.6/dist-packages/ants/viz/render_surface_function.py:16: UserWarning: Cant import Plotly. Install it `pip install plotly` if you want to use ants.render_surface_function
  warnings.warn('Cant import Plotly. Install it `pip install plotly` if you want to use ants.render_surface_function')
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.kde module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
antsRegistration --verbose 1 --float --collapse-output-transforms 1 --dimensionality 3 --initial-moving-transform [ fixed_image, moving_image, 1 ] --initialize-transforms-per-stage 0 --interpolation interpolation_method
    --transform Rigid[ 0.1 ] --metric Mattes[ fixed_image, moving_image, 1, 32, Regular, 0.3 ] --convergence [ 250x200x100, 1e-08, 20 ] --smoothing-sigmas 4.0x2.0x1.0vox --shrink-factors 4x2x1 --use-estimate-learning-rate-once 1 --use-histogram-matching 0
    --output [ transform, warped_image, inverse_warped_image ]

Warning : No task variables. Will run all sessions found in source directory /ifs/loni/faculty/thompson/four_d/yjin/PETSyn/ds001705-download
Task:
Warning : No run variables. Will process all runs found in source directory /ifs/loni/faculty/thompson/four_d/yjin/PETSyn/ds001705-download
Runs:


* Pipeline started at Thu Sep 16 22:09:03 2021on Linux c2023 3.10.0-1160.31.1.el7.x86_64

* Command line is :
 ['/opt/APPIAN/Launcher.py', '--sub', '00101', '--ses', 'baseline', '--user-ants-command', '/opt/APPIAN/src/ants_command_quick.txt', '-s', 'ds001705-download/', '-t', 'out_ds001705-download/']

* The source directory is : /ifs/loni/faculty/thompson/four_d/yjin/PETSyn/ds001705-download
* The target directory is : /ifs/loni/faculty/thompson/four_d/yjin/PETSyn/out_ds001705-download

* Data-set Subject ID(s) is/are : 00101

* Sessions :  ['baseline']

* Tasks :  []

* Runs :  []

* Acquisition :

* Reconstruction :

['baseline'] 1
     Sub       Ses  ...                                         PET Header                                         PET Volume
0  00101  baseline  ...  /ifs/loni/faculty/thompson/four_d/yjin/PETSyn/...  /ifs/loni/faculty/thompson/four_d/yjin/PETSyn/...

[1 rows x 5 columns]
210916-22:09:03,898 nipype.utils INFO:
         Running nipype version 1.4.2 (latest: 1.5.1)
results antsAtropos
pet2mri
results :, Label masking node: masking.inputnode Transformation : tfm_struct_pet
results :, Label masking node: masking.inputnode Transformation : tfm_stx_mri
mri False outputnode.brain_mask_space_stx 3
mri False mri_spatial_normalized.warped_image 3
mri False mri_spatial_normalized.inverse_warped_image 3
mri False mri_spatial_normalized.warped_image 3
datasource True pet 4
pet2mri False inverse_warped_image 3
[preproc.preinfosource, preproc.infosource, preproc.datasourcePET, preproc.datasourceAnat, preproc.datasource, initialization.inputnode, initialization.petHeader, initialization.petVolume, initialization.pet_brain_mask, initialization.outputnode, mri.inputnode, mri.mri_no_intensity_normalization, mri.mri_spatial_normalized, mri.mri_nat, mri.segmentation_ants, mri.outputnode, mri.mri_stx_brain_mask, mri.transform_brain_mask, preproc.pet2mri, preproc.pet_brain_mask_space_mri, masking.inputnode, masking.brain_mask_space_pet, masking.resultsLabels, preproc.results_datasource, preproc.t1_analysis_space, preproc._coreg_qc_metrics, preproc.visual_qc]
210916-22:09:04,190 nipype.workflow INFO:
         Workflow preproc settings: ['check', 'execution', 'logging', 'monitoring']
210916-22:09:04,226 nipype.workflow INFO:
         Running serially.
Done.
<function group_level_descriptive_statistics at 0x7f25b2f64620> True 1
<function groupLevel_visual_qc at 0x7f25e1f07730> True 1

yjin@c2023->

**Comment by wcoath** [comment]
Hi, I've just come across this same issue with a missing module when trying to run the singularity container. I can see from the above comments that it seems like the singularity container needs to be updated for it to work, is there any update on when this might happen?

Many thanks!
Will

**error message:**
/usr/local/lib/python3.6/dist-packages/ants/viz/render_surface_function.py:16: UserWarning: Cant import Plotly. Install it `pip install plotly` if you want to use ants.render_surface_function
  warnings.warn('Cant import Plotly. Install it `pip install plotly` if you want to use ants.render_surface_function')
Traceback (most recent call last):
  File "/opt/APPIAN/Launcher.py", line 5, in <module>
    from src.scanLevel import run_scan_level
  File "/opt/APPIAN/src/scanLevel.py", line 10, in <module>
    from src.workflows import Workflows
  File "/opt/APPIAN/src/workflows.py", line 6, in <module>
    import src.results as results
  File "/opt/APPIAN/src/results.py", line 8, in <module>
    from src.qc import metric_columns
  File "/opt/APPIAN/src/qc.py", line 38, in <module>
    from src.outlier import  kde, MAD
  File "/opt/APPIAN/src/outlier.py", line 9, in <module>
    from sklearn.neighbors.kde import KernelDensity
ModuleNotFoundError: No module named 'sklearn.neighbors.kde'
DEBUG   [U=14906,P=28129]  Master()                      Child exited with exit status 1
